name: Node.js CI

on:
  push:
    branches:
      - main          # ✅ Run on 'main' branch
      - 'feature/*'   # ✅ Run on 'feature/*' branches
    paths:
      - 'src/**'      # ✅ Only run if 'src/' files change
      - '!README.md'  # ❌ Exclude changes to README.md from triggering workflow
  pull_request:
    branches:
      - main          # ✅ Trigger on PR to 'main' branch
    paths:
      - 'src/**'      # ✅ Trigger if 'src/' files change

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Set up GitHub CLI
        run: |
          curl -s https://cli.github.com/install.sh | bash
          gh auth login --with-token < ${GH_TOKEN}

      - name: "Add label and comment"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token is automatically provided
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit $PR --add-label 'invalid'
          gh pr comment $PR --body 'This change is not allowed. Please review the contributing guidelines.'
    
# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests
#         run: npm test
