name: Node.js CI

on:
  push:
    branches:
      - main          # ✅ Run on 'main' branch
      - 'feature/*'   # ✅ Run on 'feature/*' branches
    paths:
      - 'src/**'      # ✅ Only run if 'src/' files change
      - '!README.md'  # ❌ Exclude changes to README.md from triggering workflow
  pull_request:
    branches:
      - main          # ✅ Trigger on PR to 'main' branch
    paths:
      - 'src/**'      # ✅ Trigger if 'src/' files change

jobs:
  triage:
    if: >-
      github.event.pull_request.user.login != 'octobot' &&
      github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: "Comment about changes we can't accept"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit $PR --add-label 'invalid'
          gh pr comment $PR --body 'It looks like you edited `package*.json`, `.github/CODEOWNERS`, or `.github/workflows/**`. We do not allow contributions to these files. Please review our [contributing guidelines](https://github.com/octo-org/octo-repo/blob/main/CONTRIBUTING.md) for what contributions are accepted.'
    
# jobs:
#   test:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '14'

#       - name: Install dependencies
#         run: npm install

#       - name: Run tests
#         run: npm test
